version: '2.1'

services:
  servidor:
    image: ubuntu
    container_name: ubuntu-servidor
    working_dir: /usr/src/servidor
    volumes:
      - .:/usr/src/servidor
    build: .
    ports:
      - 3001:3001
    tty: true
